import os
from fpdf import FPDF

out_dir = "test_documents"
if not os.path.exists(out_dir):
    os.makedirs(out_dir)

# 1. Vision and Mission
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)
pdf.cell(200, 10, txt="SIR C.R REDDY COLLEGE OF ENGINEERING", ln=True, align="C")
pdf.cell(200, 10, txt="Department of Computer Science and Engineering", ln=True, align="C")
pdf.ln(10)
pdf.set_font("Arial", 'B', 14)
pdf.cell(200, 10, txt="VISION", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="To emerge as a premier center of excellence in Computer Science and Engineering, producing highly competent professionals who can contribute to the society and industry.")
pdf.ln(5)
pdf.set_font("Arial", 'B', 14)
pdf.cell(200, 10, txt="MISSION", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="M1: To provide quality education and practical skills in cutting-edge technologies.\nM2: To foster research, innovation, and entrepreneurship among students.\nM3: To instill ethical values and leadership qualities for sustainable development.")
pdf.output(f"{out_dir}/1_Vision_Mission.pdf")

# 2. Course Syllabus
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)
pdf.cell(200, 10, txt="SIR C.R REDDY COLLEGE OF ENGINEERING", ln=True, align="C")
pdf.cell(200, 10, txt="Course Syllabus: Artificial Intelligence (CS401)", ln=True, align="C")
pdf.ln(10)
pdf.set_font("Arial", 'B', 12)
pdf.cell(200, 10, txt="Course Description:", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="This course introduces the fundamental concepts of Artificial Intelligence, including search algorithms, knowledge representation, machine learning, and neural networks.")
pdf.ln(5)
pdf.set_font("Arial", 'B', 12)
pdf.cell(200, 10, txt="Course Outcomes (COs):", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="CO1: Understand the basic principles and history of AI.\nCO2: Apply problem-solving and search strategies to real-world scenarios.\nCO3: Design expert systems using logic and knowledge representation.\nCO4: Implement basic machine learning models for classification and regression.")
pdf.output(f"{out_dir}/2_AI_Syllabus.pdf")

# 3. Faculty Profile
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)
pdf.cell(200, 10, txt="SIR C.R REDDY COLLEGE OF ENGINEERING", ln=True, align="C")
pdf.cell(200, 10, txt="Faculty Profile & Publications", ln=True, align="C")
pdf.ln(10)
pdf.set_font("Arial", 'B', 12)
pdf.cell(200, 10, txt="Name: Dr. A. Ramakrishna", ln=True)
pdf.cell(200, 10, txt="Designation: Professor & HOD", ln=True)
pdf.cell(200, 10, txt="Department: Computer Science and Engineering", ln=True)
pdf.ln(5)
pdf.cell(200, 10, txt="Recent Publications (2024-2025):", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="1. 'Deep Learning approaches for predictive analytics in healthcare', IEEE Access, 2024.\n2. 'Optimization of Cloud Resources using Genetic Algorithms', International Journal of Cloud Computing, 2025.")
pdf.ln(5)
pdf.set_font("Arial", 'B', 12)
pdf.cell(200, 10, txt="Research Grants:", ln=True)
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="Principal Investigator for AICTE RPS Grant of Rs. 15 Lakhs for 'AI-based Smart Agriculture System' (2023-2026).")
pdf.output(f"{out_dir}/3_Faculty_Profile.pdf")
